version: 2
jobs:
  fedora31:
    working_directory: ~/libreadtags
    docker:
      - image: docker.io/fedora:31
    steps:
      - run:
          name: Install Git
          command: |
            yum -y install git
      - checkout
      - run:
          name: Install build tools
          commands: |
            yum -y install gcc automake autoconf libtool make
      - run:
          name: Build
          command: |
            bash ./autogen.sh
            ./configure
            make
      - run:
          name: Test
          command: |
            make check
